# Generated by Django 4.2.7 on 2025-04-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0004_booking_status_booking_updates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='lr_no',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
