# Generated by Django 4.2.7 on 2025-07-08 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0007_remove_shipmentdetails_misc_charges_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='delivery_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='delivery_address',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pickup_address',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
