version: '3.8'
services:
  backend:
    build:
      context: ./shipment_project
    env_file:
      - ./shipment_project/.env
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
  frontend:
    build:
      context: ./src
    env_file:
      - ./src/.env
    ports:
      - "80:80"
    depends_on:
      - backend
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_NAME:-shipment_db}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: